name: Test

on: [push]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true

  integration:
    runs-on: ubuntu-latest

    services:
      vault:
        image: vault:1.2.3
        ports:
          - 8200/tcp
        env:
          VAULT_DEV_ROOT_TOKEN_ID: testtoken
        options: --cap-add=IPC_LOCK

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: npm ci
    - name: npm run test:integration
      run: npm run test:integration
      env:
        VAULT_HOST: localhost
        VAULT_PORT: ${{ job.services.vault.ports[8200] }}

  e2e:
    runs-on: ubuntu-latest

    services:
      vault:
        image: vault:1.2.3
        ports:
          - 8200/tcp
        env:
          VAULT_DEV_ROOT_TOKEN_ID: testtoken
        options: --cap-add=IPC_LOCK

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: npm ci
    - name: setup vault
      run: node ./e2e/setup.js
      env:
        VAULT_HOST: localhost
        VAULT_PORT: ${{ job.services.vault.ports[8200] }}
    - name: use vault actions
      uses: ./
    - name: verify
      run: npm run test:e2e

  

